// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpwajaymzericmluolhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwd2FqYXltemVyaWNtbHVvbGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTEzOTMsImV4cCI6MjA3MTI4NzM5M30.DQQ6K1BFyyC_XiQwD8_phce4BIqe6TNcjrFrEMpxKF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});